//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.FilterBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.FilterBuilder.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contains 的本地化字符串。
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndsWith 的本地化字符串。
        /// </summary>
        public static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EqualTo 的本地化字符串。
        /// </summary>
        public static string EqualTo {
            get {
                return ResourceManager.GetString("EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GreaterThan 的本地化字符串。
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GreaterThanOrEqualTo 的本地化字符串。
        /// </summary>
        public static string GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsEmpty 的本地化字符串。
        /// </summary>
        public static string IsEmpty {
            get {
                return ResourceManager.GetString("IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsNull 的本地化字符串。
        /// </summary>
        public static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LessThan 的本地化字符串。
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LessThanOrEqualTo 的本地化字符串。
        /// </summary>
        public static string LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotEqualTo 的本地化字符串。
        /// </summary>
        public static string NotEqualTo {
            get {
                return ResourceManager.GetString("NotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotIsEmpty 的本地化字符串。
        /// </summary>
        public static string NotIsEmpty {
            get {
                return ResourceManager.GetString("NotIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotIsNull 的本地化字符串。
        /// </summary>
        public static string NotIsNull {
            get {
                return ResourceManager.GetString("NotIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Or 的本地化字符串。
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartsWith 的本地化字符串。
        /// </summary>
        public static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
    }
}
