//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.FilterBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.FilterBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add expression.
        /// </summary>
        internal static string FilterBuilder_AddExpression {
            get {
                return ResourceManager.GetString("FilterBuilder_AddExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group.
        /// </summary>
        internal static string FilterBuilder_AddGroup {
            get {
                return ResourceManager.GetString("FilterBuilder_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string FilterBuilder_And {
            get {
                return ResourceManager.GetString("FilterBuilder_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string FilterBuilder_AreYouSure {
            get {
                return ResourceManager.GetString("FilterBuilder_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string FilterBuilder_Contains {
            get {
                return ResourceManager.GetString("FilterBuilder_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item.
        /// </summary>
        internal static string FilterBuilder_DeleteItem {
            get {
                return ResourceManager.GetString("FilterBuilder_DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter has unsaved changes. Are you sure you want to close the editor without saving changes?.
        /// </summary>
        internal static string FilterBuilder_DiscardChanges {
            get {
                return ResourceManager.GetString("FilterBuilder_DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not contain.
        /// </summary>
        internal static string FilterBuilder_DoesNotContain {
            get {
                return ResourceManager.GetString("FilterBuilder_DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not end with.
        /// </summary>
        internal static string FilterBuilder_DoesNotEndWith {
            get {
                return ResourceManager.GetString("FilterBuilder_DoesNotEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not match.
        /// </summary>
        internal static string FilterBuilder_DoesNotMatch {
            get {
                return ResourceManager.GetString("FilterBuilder_DoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not start with.
        /// </summary>
        internal static string FilterBuilder_DoesNotStartWith {
            get {
                return ResourceManager.GetString("FilterBuilder_DoesNotStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends with.
        /// </summary>
        internal static string FilterBuilder_EndsWith {
            get {
                return ResourceManager.GetString("FilterBuilder_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is equal to.
        /// </summary>
        internal static string FilterBuilder_EqualTo {
            get {
                return ResourceManager.GetString("FilterBuilder_EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        internal static string FilterBuilder_FieldIsRequired {
            get {
                return ResourceManager.GetString("FilterBuilder_FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is greater than.
        /// </summary>
        internal static string FilterBuilder_GreaterThan {
            get {
                return ResourceManager.GetString("FilterBuilder_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is greater than or equal to.
        /// </summary>
        internal static string FilterBuilder_GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterBuilder_GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is empty.
        /// </summary>
        internal static string FilterBuilder_IsEmpty {
            get {
                return ResourceManager.GetString("FilterBuilder_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is null.
        /// </summary>
        internal static string FilterBuilder_IsNull {
            get {
                return ResourceManager.GetString("FilterBuilder_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less than.
        /// </summary>
        internal static string FilterBuilder_LessThan {
            get {
                return ResourceManager.GetString("FilterBuilder_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less than or equal to.
        /// </summary>
        internal static string FilterBuilder_LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterBuilder_LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live preview.
        /// </summary>
        internal static string FilterBuilder_LivePreview {
            get {
                return ResourceManager.GetString("FilterBuilder_LivePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matches.
        /// </summary>
        internal static string FilterBuilder_Matches {
            get {
                return ResourceManager.GetString("FilterBuilder_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FilterBuilder_Name {
            get {
                return ResourceManager.GetString("FilterBuilder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not equal to.
        /// </summary>
        internal static string FilterBuilder_NotEqualTo {
            get {
                return ResourceManager.GetString("FilterBuilder_NotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not empty.
        /// </summary>
        internal static string FilterBuilder_NotIsEmpty {
            get {
                return ResourceManager.GetString("FilterBuilder_NotIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not null.
        /// </summary>
        internal static string FilterBuilder_NotIsNull {
            get {
                return ResourceManager.GetString("FilterBuilder_NotIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string FilterBuilder_Or {
            get {
                return ResourceManager.GetString("FilterBuilder_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter has some invalid expressions which will be ignored while filtering. Are you sure you want to save this filter?.
        /// </summary>
        internal static string FilterBuilder_SaveBroken {
            get {
                return ResourceManager.GetString("FilterBuilder_SaveBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts with.
        /// </summary>
        internal static string FilterBuilder_StartsWith {
            get {
                return ResourceManager.GetString("FilterBuilder_StartsWith", resourceCulture);
            }
        }
    }
}
